import test from 'node:test';
import assert from 'node:assert/strict';
import {newGame,makeDeck,face,canPlay,applyAction,viewGame,colors,scoreFace,nextRound} from '../lib/game.ts';
import {handCardInfo} from '../lib/card-effects.ts';
const names=['A','B','C','D'].map((name,avatar)=>({name,avatar}));
const c=(id,color,kind='number',n=3,extra={})=>({id,a:{color,kind,n,...extra}});
function state(mode='classic',stacking=false){const g=newGame(mode,names,{dealer:3,stacking});g.turn=0;g.phase='playing';g.dir=1;g.side=0;g.color='red';g.pending=null;g.discard=[c('top','red','number',5)];g.players.forEach(p=>{p.hand=[c('s'+p.name,'blue','number',7),c('t'+p.name,'yellow','number',2)];p.power=true});return g}
test('deck counts, unique cards, FLIP two full sides, FLEX 1–8',()=>{for(const [mode,n] of [['classic',108],['flip',112],['flex',104]]){const d=makeDeck(mode);assert.equal(d.length,n);assert.equal(new Set(d.map(c=>c.id)).size,n);if(mode==='flip')assert.equal(d.filter(c=>c.b).length,112);if(mode==='flex')assert.ok(d.every(c=>c.a.kind!=='number'||(c.a.n>=1&&c.a.n<=8)))}});
test('matching rejects wrong color/number and out of turn',()=>{const g=state();const card=c('x','blue','number',3);assert.equal(canPlay(g,0,card),false);assert.equal(canPlay(g,1,c('a','red')),false);assert.throws(()=>applyAction(g,1,{type:'draw'}));assert.equal(canPlay(g,0,c('x','blue','number',5)),true)});
test('drawn card is the only playable card after a draw',()=>{let g=state();g.players[0].hand=[c('old','red'),c('hold','yellow')];g.deck.push(c('new','red'));g=applyAction(g,0,{type:'draw'});assert.equal(g.drawn,'new');assert.equal(canPlay(g,0,g.players[0].hand[0]),false);assert.equal(canPlay(g,0,g.players[0].hand.at(-1)),true);assert.throws(()=>applyAction(g,0,{type:'draw'}));g=applyAction(g,0,{type:'pass'});assert.equal(g.turn,1)});
test('official penalties cannot be stacked and skip after acceptance',()=>{let g=state();g.players[0].hand.push(c('atk','red','draw2'));g.players[1].hand.push(c('stack','blue','draw2'));g=applyAction(g,0,{type:'play',id:'atk'});assert.equal(canPlay(g,1,g.players[1].hand.at(-1)),false);const n=g.players[1].hand.length;g=applyAction(g,1,{type:'accept'});assert.equal(g.players[1].hand.length,n+2);assert.equal(g.turn,2)});
test('house stacking adds same types and rejects mixed values',()=>{let g=state('classic',true);g.players[0].hand.push(c('atk','red','draw2'));g.players[1].hand.push(c('stack','blue','draw2'),c('mix','wild','wild4'));g=applyAction(g,0,{type:'play',id:'atk'});assert.equal(canPlay(g,1,g.players[1].hand.at(-1)),false);g=applyAction(g,1,{type:'play',id:'stack'});assert.equal(g.pending.amount,4);g=applyAction(g,2,{type:'accept'});assert.equal(g.players[2].hand.length,6);assert.equal(g.turn,3)});
test('successful and failed Wild Draw Four challenges',()=>{for(const illegal of [true,false]){let g=state();g.players[0].hand=[c('wd','wild','wild4'),c('held',illegal?'red':'blue')];g=applyAction(g,0,{type:'play',id:'wd',color:'green'});assert.equal(g.pending.illegal,illegal);g=applyAction(g,1,{type:'challenge'});assert.equal(g.turn,illegal?1:2);assert.equal(g.players[illegal?0:1].hand.length,illegal?5:8);assert.ok(viewGame(g,1).reveal);assert.equal(viewGame(g,2).reveal,null)}});
test('FLEX ordinary Wild Draw Four considers other wilds a match',()=>{let g=state('flex');g.players[0].hand=[c('wd','wild','wild4',0,{flex:'wild4'}),c('wild','wild','allFlip')];g=applyAction(g,0,{type:'play',id:'wd',color:'blue'});assert.equal(g.pending.illegal,true)});
test('FLEX secondary color matches but primary color continues',()=>{let g=state('flex');g.players[0].hand.push(c('fl','yellow','number',8,{alt:'red',flex:'color'}));assert.equal(canPlay(g,0,g.players[0].hand.at(-1)),false);g=applyAction(g,0,{type:'play',id:'fl',flex:true});assert.equal(g.color,'yellow');assert.equal(g.players[0].power,false);assert.equal(g.turn,1)});
test('FLEX target draw does not skip and ignores ordinary WDF restriction',()=>{let g=state('flex');g.players[0].hand=[c('wd','wild','wild4',0,{flex:'wild4'}),c('held','red')];g=applyAction(g,0,{type:'play',id:'wd',flex:true,color:'green',target:1});assert.equal(g.turn,1);assert.equal(g.players[1].hand.length,6);assert.equal(g.pending,null);assert.equal(g.players[0].power,false)});
test('FLEX group draw and all-red reset',()=>{let g=state('flex');g.players.slice(1).forEach(p=>p.power=false);g.players[0].hand.push(c('all','red','draw2',0,{flex:'draw2'}));g=applyAction(g,0,{type:'play',id:'all',flex:true});assert.equal(g.turn,1);assert.ok(g.players.every(p=>p.power));assert.ok(g.players.slice(1).every(p=>p.hand.length===3))});
test('FLEX reverse skips first player in new direction',()=>{let g=state('flex');g.players[0].hand.push(c('r','red','reverse',0,{flex:'reverse'}));g=applyAction(g,0,{type:'play',id:'r',flex:true});assert.equal(g.dir,-1);assert.equal(g.turn,2)});
test('FLEX skip everyone gives same player a new turn',()=>{let g=state('flex');g.players[0].hand.push(c('s','red','skip',0,{flex:'skip'}));g=applyAction(g,0,{type:'play',id:'s',flex:true});assert.equal(g.turn,0)});
test('FLIP reverses physical draw/discard order and exposes old bottom',()=>{let g=state('flip');const back=color=>({color,kind:'number',n:7});g.discard=[{...c('oldbottom','blue'),b:back('purple')},{...c('oldtop','red'),b:back('teal')}];g.players[0].hand.push({...c('flip','red','flip'),b:back('orange')});const first=g.deck[0].id;g=applyAction(g,0,{type:'play',id:'flip'});assert.equal(g.side,1);assert.equal(g.discard.at(-1).id,'oldbottom');assert.equal(g.discard[0].id,'flip');assert.equal(g.deck.at(-1).id,first);assert.equal(g.color,'purple')});
test('FLIP draw-color stops on selected color and skips',()=>{let g=state('flip');g.side=1;g.color='purple';g.discard=[{id:'t',a:{color:'red',kind:'number',n:2},b:{color:'purple',kind:'number',n:2}}];g.players[0].hand=[{id:'wc',a:{color:'red',kind:'number',n:5},b:{color:'wild',kind:'wildColor'}},c('held','blue')];g.deck=[c('x','teal'),c('y','orange'),c('z','pink')];g=applyAction(g,0,{type:'play',id:'wc',color:'teal'});g=applyAction(g,1,{type:'accept'});assert.equal(g.players[1].hand.length,5);assert.equal(g.turn,2)});
test('UNO catch window closes when next player acts',()=>{let g=state();g.players[0].hand=[c('play','red'),c('left','blue')];g=applyAction(g,0,{type:'play',id:'play'});assert.equal(g.unoVulnerable,0);const caught=applyAction(g,1,{type:'catch'});assert.equal(caught.players[0].hand.length,3);g=applyAction(g,1,{type:'draw'});assert.throws(()=>applyAction(g,2,{type:'catch'}))});
test('UNO can be predeclared and saves penalty',()=>{let g=state();g.players[0].hand=[c('play','red'),c('left','blue')];g=applyAction(g,0,{type:'uno'});g=applyAction(g,0,{type:'play',id:'play'});assert.equal(g.unoVulnerable,null);assert.equal(g.players[0].called,true)});
test('final draw card settles before scoring; no stack after going out',()=>{let g=state('classic',true);g.players[0].hand=[c('last','red','draw2')];g.players[1].hand.push(c('stack','red','draw2'));g=applyAction(g,0,{type:'play',id:'last'});assert.equal(g.phase,'playing');assert.equal(canPlay(g,1,g.players[1].hand.at(-1)),false);g=applyAction(g,1,{type:'accept'});assert.equal(g.phase,'over');assert.equal(g.winner,0);assert.ok(g.players[0].score>0);assert.equal(nextRound(g).players[0].score,0)});
test('private projection hides other hands, deck and challenge truth',()=>{let g=state();g.players[0].hand.push(c('wd','wild','wild4'));g=applyAction(g,0,{type:'play',id:'wd',color:'red'});const v=viewGame(g,1);assert.equal(v.players[0].hand.length,0);assert.equal(v.players[1].hand.length,2);assert.equal(v.pending.illegal,undefined);assert.equal(v.pending.proof,undefined);assert.equal(v.deck,undefined)});
test('scores are based on the active face',()=>{assert.equal(scoreFace({color:'wild',kind:'wildColor'},'flip'),60);assert.equal(scoreFace({color:'red',kind:'draw1'},'flip'),10);assert.equal(scoreFace({color:'purple',kind:'skipAll'},'flip'),30)});
test('selected FLEX description follows normal, boosted and exhausted states',()=>{
 const g=state('flex'),card=c('preview','red','draw2',0,{flex:'draw2'});g.players[0].hand.push(card);
 const normal=handCardInfo(card,viewGame(g,0),0,false);assert.match(normal.detail,/下一位摸 2 张并跳过/);assert.equal(normal.boosted,false);
 const boosted=handCardInfo(card,viewGame(g,0),0,true);assert.match(boosted.detail,/其余三人各摸 1 张，下一位照常/);assert.equal(boosted.boosted,true);
 const result=applyAction(g,0,{type:'play',id:card.id,flex:true});assert.equal(result.turn,1);assert.equal(result.pending,null);assert.ok(result.players.slice(1).every(p=>p.hand.length===3));
 g.players[0].power=false;const exhausted=handCardInfo(card,viewGame(g,0),0,true);assert.equal(exhausted.boosted,false);assert.match(exhausted.detail,/能量已耗尽，当前仅普通/);assert.match(exhausted.detail,/下一位摸 2 张并跳过/);
});
test('preview matches actual secondary-color legality, plain cards and energy reset',()=>{
 const g=state('flex'),alt=c('alt','yellow','number',8,{alt:'red',flex:'color'}),plain=c('plain','red','number',4,{power:true});g.players[0].hand.push(alt,plain);
 assert.equal(handCardInfo(alt,viewGame(g,0),0,false).playable,false);assert.equal(handCardInfo(alt,viewGame(g,0),0,true).playable,true);
 assert.match(handCardInfo(alt,viewGame(g,0),0,true).detail,/出牌后跟黄色/);
 assert.equal(handCardInfo(plain,viewGame(g,0),0,true).boosted,false);assert.equal(handCardInfo(plain,viewGame(g,0),0,true).playable,true);
 g.players.slice(1).forEach(p=>p.power=false);assert.match(handCardInfo(alt,viewGame(g,0),0,true).detail,/全员耗尽将自动恢复/);
 assert.match(handCardInfo(plain,viewGame(g,0),0,true).detail,/将全员恢复/);
});
test('FLIP outward faces update after flip and draw without exposing active hands',()=>{
 let g=newGame('flip',names,{dealer:3},()=>0.42);g.phase='playing';g.side=0;g.color='red';g.turn=0;g.pending=null;
 const flipCard=g.players[0].hand.find(c=>c.a.kind==='flip')??g.deck.find(c=>c.a.kind==='flip');
 if(!g.players[0].hand.includes(flipCard)){g.deck=g.deck.filter(c=>c.id!==flipCard.id);g.players[0].hand.push(flipCard)}g.color=flipCard.a.color;
 function verify(){for(let viewer=0;viewer<4;viewer++){const v=viewGame(g,viewer);for(let i=0;i<4;i++){assert.deepEqual(v.players[i].backs,i===viewer?[]:g.players[i].hand.map(c=>face(c,1-g.side)));assert.equal(v.players[i].hand.length,i===viewer?g.players[i].hand.length:0);}}}
 verify();g=applyAction(g,0,{type:'play',id:flipCard.id});assert.equal(g.side,1);verify();if(g.phase==='color')g=applyAction(g,g.turn,{type:'color',color:'teal'});g=applyAction(g,g.turn,{type:'draw'});verify();
});
test('300 simulated four-player games preserve cards and finish',()=>{for(const mode of ['classic','flip','flex'])for(let round=0;round<100;round++){let g=newGame(mode,names,{stacking:round%2===0});const total=makeDeck(mode).length;let turns=0;while(g.phase!=='over'&&turns++<2500){const who=g.turn;let action;if(g.phase==='color')action={type:'color',color:colors(g)[0]};else{let plays=g.players[who].hand.flatMap(c=>[false,true].filter(f=>canPlay(g,who,c,f)).map(f=>({c,f})));if(g.pending&&!plays.length)action={type:g.pending.challenge&&Math.random()<.5?'challenge':'accept'};else if(plays.length){const choice=plays[Math.floor(Math.random()*plays.length)];action={type:'play',id:choice.c.id,flex:choice.f,color:colors(g)[Math.floor(Math.random()*4)],target:(who+1)%4,uno:true}}else action={type:g.drawn?'pass':'draw'}}g=applyAction(g,who,action);const all=[...g.deck,...g.discard,...g.players.flatMap(p=>p.hand)];assert.equal(all.length,total);assert.equal(new Set(all.map(c=>c.id)).size,total);assert.ok(g.turn>=0&&g.turn<4)}assert.equal(g.phase,'over',`${mode} did not end`);assert.equal(g.players[g.winner].hand.length,0)}});
