"use client";
import {useEffect,useRef,useState} from 'react';
import type {CSSProperties} from 'react';
import {Gamepad2,Layers,BookOpen,Volume2,VolumeX,Settings2,Users,Wifi,Monitor,Zap,Rotate3d,Copy,LogOut,History,Eye,Shield,Check,RefreshCw,Repeat2,Flag} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {newGame,nextRound,applyAction,viewGame,face,label,colors,COLOR_NAMES,type Mode,type Game,type GameView,type Card,type Action,type Color,type Event} from '@/lib/game';
import {PlayingCard,SeatBadge,CameoArt,CAMEOS,EggGallery} from './cards';
import Rules from './rules';
type Room={code:string;mode:Mode;seats:({name:string;avatar:number;ready:boolean}|null)[];host:number;viewer:number;revision:number;stacking:boolean;match500:boolean;game:GameView|null};
type Modal='online'|'local'|'rules'|'settings'|'log'|'leave'|'eggs'|null;
const NAMES=['玩家 1','玩家 2','玩家 3','玩家 4'];
const TITLES={classic:'经典 UNO',flip:'UNO FLIP',flex:'UNO FLEX'};
const ROUTES={classic:'/',flip:'/flip',flex:'/flex'};
const symbols:Record<Color,string>={red:'●',yellow:'◆',green:'▲',blue:'■',pink:'●',teal:'◆',orange:'▲',purple:'■',wild:'✦'};
export default function Arcade({mode}:{mode:Mode}){
 const [modal,setModal]=useState<Modal>(null),[tab,setTab]=useState('create');
 const [names,setNames]=useState([...NAMES]),[name,setName]=useState(''),[joinCode,setJoinCode]=useState('');
 const [stacking,setStacking]=useState(false),[match500,setMatch500]=useState(false);
 const [room,setRoom]=useState<Room|null>(null),[local,setLocal]=useState<Game|null>(null),[masked,setMasked]=useState(true);
 const [busy,setBusy]=useState(false),[connected,setConnected]=useState(true),[useFlex,setUseFlex]=useState(false);
 const [pick,setPick]=useState<{card:Card;flex:boolean}|null>(null),[chosen,setChosen]=useState<Color|null>(null),[target,setTarget]=useState<number|null>(null);
 const [sound,setSound]=useState(false),[effects,setEffects]=useState(true),[fx,setFx]=useState<Event|null>(null);
 const token=useRef(''),roomRef=useRef<Room|null>(null),lastFx=useRef(''),audio=useRef<AudioContext|null>(null),pendingPoll=useRef(false);
 const game=local?viewGame(local,local.turn):room?.game??null;
 const viewer=local?local.turn:room?.viewer??0;
 const myTurn=!!game&&game.turn===viewer&&game.phase!=='over'&&(!local||!masked);
 const my=game?.players[viewer];
 const receive=(r:Room)=>{if(!roomRef.current||r.code!==roomRef.current.code||r.revision>=roomRef.current.revision){roomRef.current=r;setRoom(r)}setConnected(true)};
 async function refresh(code:string,t=token.current){const response=await fetch(`/api/room?code=${code}`,{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});const data=await response.json() as Room & {error?:string;token?:string;left?:boolean};if(!response.ok)throw Error(data.error);receive(data);return data as Room}
 useEffect(()=>{
  try{const prefs=JSON.parse(localStorage.getItem('uno-prefs')??'{}');setSound(prefs.sound??false);setEffects(prefs.effects??!matchMedia('(prefers-reduced-motion: reduce)').matches);
   const c=new URLSearchParams(location.search).get('room');
   if(c){setJoinCode(c.toUpperCase());const saved=JSON.parse(sessionStorage.getItem(`uno-room-${c}`)??'null');if(saved?.token){token.current=saved.token;refresh(c,saved.token).catch(()=>{setModal('online');setTab('join');toast.error('重连失败，请检查房间号或重新入座')})}else{setModal('online');setTab('join')}}
   else{const saved=JSON.parse(localStorage.getItem(`uno-local-${mode}`)??'null');if(saved?.players?.length===4&&saved.mode===mode){if(saved.players.every((p:{name:string},i:number)=>p.name===CAMEOS[i]))saved.players.forEach((p:{name:string},i:number)=>{p.name=NAMES[i]});if(saved.players.every((p:{name:string},i:number)=>p.name===NAMES[i]))saved.events.forEach((e:Event)=>{e.text=CAMEOS.reduce((text,n,i)=>text.replaceAll(n,NAMES[i]),e.text)});setLocal(saved);setMasked(true)}}
  }catch{/* Ignore invalid device-local preferences. */}
 },[mode]);
 useEffect(()=>{if(local)try{localStorage.setItem(`uno-local-${mode}`,JSON.stringify(local))}catch{}},[local,mode]);
 useEffect(()=>{if(!room?.code)return;let active=true;const code=room.code;const run=async()=>{if(pendingPoll.current)return;pendingPoll.current=true;try{const response=await fetch(`/api/room?code=${code}`,{headers:{Authorization:`Bearer ${token.current}`},cache:'no-store'});const data=await response.json() as Room & {error?:string;token?:string;left?:boolean};if(!response.ok)throw Error();if(active)receive(data)}catch{if(active)setConnected(false)}finally{pendingPoll.current=false}};const timer=setInterval(run,1100);return()=>{active=false;clearInterval(timer)}},[room?.code]);
 function tone(type:string){if(!sound)return;try{const ctx=audio.current??new AudioContext();audio.current=ctx;void ctx.resume();const osc=ctx.createOscillator(),gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.type=['damage','stack'].includes(type)?'sawtooth':'triangle';const freq=type==='flip'?240:type==='flex'?600:type==='damage'?100:440;osc.frequency.setValueAtTime(freq,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(type==='damage'?40:freq*1.8,ctx.currentTime+.18);gain.gain.setValueAtTime(.055,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.3);osc.start();osc.stop(ctx.currentTime+.31)}catch{}}
 useEffect(()=>{if(!game)return;const key=`${game.round}-${game.revision}-${game.events.at(-1)?.id}`;if(lastFx.current===key)return;const prev=lastFx.current;lastFx.current=key;if(!prev)return;const batch=game.events.filter(e=>e.id>(Number(prev.split('-')[2])||0));const priority=['win','flip','flex','stack','damage','uno','reverse','attack','play'];const e=priority.map(t=>batch.findLast(x=>x.type===t)).find(Boolean);if(e){tone(e.type);if(effects)setFx({...e,cameo:batch.findLast(x=>x.type==='play')?.cameo})}setUseFlex(false)},[game?.revision,game?.round,effects]);
 useEffect(()=>{if(!fx)return;const t=setTimeout(()=>setFx(null),fx.type==='flip'?1500:1100);return()=>clearTimeout(t)},[fx]);
 async function roomOp(op:string,extra:Record<string,unknown>={}){
  if(busy)return;setBusy(true);try{const current=roomRef.current;const response=await fetch('/api/room',{method:'POST',headers:{'Content-Type':'application/json',...(token.current?{Authorization:`Bearer ${token.current}`}:{})},body:JSON.stringify({op,code:current?.code,revision:current?.revision,requestId:crypto.randomUUID(),...extra})});const data=await response.json() as Room & {error?:string;token?:string;left?:boolean};if(!response.ok){if(response.status===409&&current)await refresh(current.code);if(data.mode&&data.mode!==mode){location.href=`${ROUTES[data.mode as Mode]}?room=${encodeURIComponent(joinCode.toUpperCase())}`;return}throw Error(data.error??'操作失败，请重试')}
   if(data.token){token.current=data.token;sessionStorage.setItem(`uno-room-${data.code}`,JSON.stringify({token:data.token}));history.replaceState(null,'',`${ROUTES[mode]}?room=${data.code}`)}
   if(data.left){sessionStorage.removeItem(`uno-room-${current?.code}`);token.current='';roomRef.current=null;setRoom(null);history.replaceState(null,'',ROUTES[mode])}else receive(data);
   setModal(null);return data;
  }catch(e){toast.error(e instanceof Error?e.message:'连接失败，请重试')}finally{setBusy(false)}
 }
 async function act(action:Action){
  if(busy)return;try{if(local){const updated=applyAction(local,viewer,action);setLocal(updated);if(updated.turn!==local.turn&&updated.phase!=='over')setMasked(true)}else await roomOp('action',{action});setPick(null);setUseFlex(false)}catch(e){toast.error(e instanceof Error?e.message:'无法操作')}
 }
 function startLocal(){if(names.some(n=>!n.trim())){toast.error('请填写四位玩家的昵称');return}lastFx.current='';setLocal(newGame(mode,names.map((n,i)=>({name:n.trim(),avatar:i})),{stacking,match500}));setMasked(true);setModal(null)}
 function play(card:Card){if(!myTurn)return;const flex=useFlex;const f=face(card,game!.side);if(f.color==='wild'){setPick({card,flex});setChosen(null);setTarget(null)}else void act({type:'play',id:card.id,flex})}
 function next(){lastFx.current='';if(local){setLocal(nextRound(local));setMasked(true)}else void roomOp('next')}
 async function invite(){if(!room)return;const url=`${location.origin}${ROUTES[mode]}?room=${room.code}`;try{await navigator.clipboard.writeText(url);toast.success('邀请链接已复制')}catch{toast(url,{duration:12000})}}
 function leave(){if(room&&!game){void roomOp('leave');return}if(local){localStorage.removeItem(`uno-local-${mode}`);setLocal(null)}if(room){roomRef.current=null;setRoom(null);history.replaceState(null,'',ROUTES[mode])}setModal(null);lastFx.current=''}
 function prefs(key:'sound'|'effects',value:boolean){const s=key==='sound'?value:sound,e=key==='effects'?value:effects;setSound(s);setEffects(e);localStorage.setItem('uno-prefs',JSON.stringify({sound:s,effects:e}));if(key==='sound'&&value){try{audio.current??=new AudioContext();void audio.current.resume()}catch{}}}
 const visibleRef=useRef<unknown>(null); visibleRef.current={mode,room:room?.code??null,game:local&&masked?{turn:game?.turn,masked:true}:game};
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options?:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:'read_uno_table',description:'读取当前可见牌局、自己的手牌与可用动作，不暴露其他玩家手牌。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:Record<string,unknown>)=>{if(input&&Object.keys(input).length)throw Error('此工具不接受参数');return visibleRef.current}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
 const seats=game?.players??room?.seats??NAMES.map((n,i)=>({name:n,avatar:i,ready:false}));
 const needTarget=pick?.flex&&['target2','wild4'].includes(face(pick.card,game?.side).kind);
 const activeFx=effects?fx:null;
 return <main className={`arcade mode-${mode} ${game?'in-game':''} ${game?.side?'dark-side':''} ${activeFx&&['damage','stack'].includes(activeFx.type)?'shake':''}`}><Toaster theme="dark" position="top-center"/>
 <aside className="rail"><a className="brand-icon" href="/" aria-label="UNO CLUB"><Gamepad2/></a><div className="rail-line"/>{([['classic',Layers],['flip',Rotate3d],['flex',Zap]] as const).map(([m,Icon])=><a key={m} className={`rail-item ${m===mode?'selected':''}`} href={ROUTES[m]} title={TITLES[m]} aria-label={TITLES[m]}><Icon/></a>)}</aside>
 <div className="workspace"><header className="topbar"><a className="wordmark" href="/">UNO <b>CLUB<span>+</span></b></a><nav>{(['classic','flip','flex'] as Mode[]).map(m=><a key={m} className={mode===m?'active':''} href={ROUTES[m]}>{TITLES[m]}{m==='flex'&&<Zap size={14}/>}</a>)}</nav><div className="header-tools"><button aria-label="游戏规则" title="游戏规则" onClick={()=>setModal('rules')}><BookOpen size={19}/></button><button aria-label={sound?'关闭声音':'开启声音'} title={sound?'关闭声音':'开启声音'} onClick={()=>prefs('sound',!sound)}>{sound?<Volume2 size={19}/>:<VolumeX size={19}/>}</button><button aria-label="设置" title="设置" onClick={()=>setModal('settings')}><Settings2 size={19}/></button></div></header>
 <div className="room-strip"><div className="room-info"><h1>{room?`房间 ${room.code}`:local?'同屏四人':TITLES[mode]}</h1>{game&&<span className="tag">第 {game.round} 局</span>}{(game?.stacking??room?.stacking)&&<span className="rule-chip">叠加房规</span>}{room&&!connected&&<span className="disconnect">连接中断 · 正在重连</span>}</div><div className="room-controls">{room&&<button className="ghost" onClick={invite}><Copy size={15}/><span>邀请</span></button>}{game&&<button className="icon-button" aria-label="对局记录" onClick={()=>setModal('log')}><History size={18}/></button>}{(room||local)&&<button className="icon-button" aria-label="离开牌桌" onClick={()=>setModal('leave')}><LogOut size={18}/></button>}</div></div>
 <section className="table-stage"><div className="table-grid"/><div className="orbit orbit-one"/><div className="orbit orbit-two"/>
 {seats.map((s,i)=><div className={`seat seat-${i} ${game&&game.turn===i&&game.phase!=='over'?'current':''} ${game&&game.unoVulnerable===i?'vulnerable':''}`} key={i}><SeatBadge seat={i}/><div className="seat-info"><b>{s?.name??'空座位'}<small>{(room&&viewer===i)?'你':`P${i+1}`}</small></b><span>{game?<><strong>{game.players[i].count}</strong> 张{game.mode==='flex'&&<em className={game.players[i].power?'charged':'empty'}>{game.players[i].power?'⚡ 可强化':'× 已耗尽'}</em>}</>:room?(s?(room?.seats[i]?.ready?'已准备':'未准备'):'等待加入'):'等待入座'}</span>{game&&<small className="seat-score">{game.players[i].score} 分 {game.players[i].called&&<mark>UNO!</mark>}</small>}</div>{room&&!game&&room.seats[i]?.ready&&<Check className="ready-check" size={16}/>}</div>)}
 {!game&&!room&&<div className="center-start"><div className={`uno-title title-${mode}`}>UNO<span>{mode==='classic'?'!':mode.toUpperCase()}</span></div><div className="start-actions"><button className="primary" onClick={()=>{setModal('online');setTab('create')}}><Wifi size={18}/> 在线联机</button><button className="secondary" onClick={()=>setModal('local')}><Monitor size={18}/> 同屏四人</button></div><button className="text-button" onClick={()=>setModal('rules')}>玩法说明</button></div>}
 {room&&!game&&<div className="center-start lobby-center"><div className="lobby-count">{room.seats.filter(Boolean).length}<span> / 4</span></div><h2>等待玩家入座</h2><p className="room-code">{room.code}</p><div className="start-actions"><button className="secondary" onClick={invite}><Copy size={17}/> 复制邀请</button><button className="primary" disabled={busy} onClick={()=>roomOp('ready')}>{room.seats[viewer]?.ready?'取消准备':'我准备好了'}</button></div>{room.host===viewer&&<button className="start-game-button" disabled={busy||room.seats.some(s=>!s||!s.ready)} onClick={()=>roomOp('start')}>四人开局</button>}<p className="lobby-note">四人全部准备后，由房主开始</p></div>}
 {game&&<><div className="game-center"><div className="table-state"><span className={`color-indicator color-${game.color}`}>{symbols[game.color]} {COLOR_NAMES[game.color]}色</span><span><Repeat2 size={14}/> {game.dir===1?'顺时针':'逆时针'}</span>{mode==='flip'&&<span className="side-label">{game.side?'暗面':'明面'}</span>}</div><div className="piles"><button className="draw-pile" aria-label={game.pending?'接受加牌':'摸一张牌'} disabled={!myTurn||busy||!!game.drawn||game.phase==='color'} onClick={()=>act({type:game.pending?'accept':'draw'})}><span>UNO</span><small>{game.deckCount} 张</small></button><div className="discard-wrap" key={`${game.top.id}-${game.side}`}><PlayingCard card={game.top} side={game.side}/><span className="pile-label">弃牌堆</span></div></div>{game.pending&&<div className="pending-badge">{game.pending.kind==='wildColor'?`抽至${COLOR_NAMES[game.pending.color!]}色`:`累计 +${game.pending.amount}`}<small>{game.players[game.pending.target].name} 接招</small></div>}<div className="turn-message" role="status">{game.phase==='over'?'本局结束':local&&masked?'等待交接':myTurn?(game.pending?'接牌，或接受惩罚':game.drawn?'打出刚摸的牌，或过牌':game.phase==='color'?'请选择颜色':'轮到你出牌'): `等待 ${game.players[game.turn].name} 出牌`}</div></div>
 {mode==='flip'&&(!local||!masked)&&<button className="peek-backs" onClick={()=>setModal('log')}><Eye size={14}/> 查看对手背面</button>}
 <div className="last-action">{game.events.at(-1)?.text}</div>
 {local&&masked&&game.phase!=='over'&&<div className="handoff"><SeatBadge seat={viewer}/><Shield size={22}/><h2>交给 {game.players[viewer].name}</h2><p>请其他玩家移开视线</p><button className="primary" onClick={()=>setMasked(false)}><Eye size={17}/> 我已接手，查看手牌</button></div>}
 {game.phase==='over'&&<div className="victory-panel"><Flag size={28}/><span>{game.matchWinner!==null?'VICTORY':'ROUND CLEAR'}</span><h2>{game.players[game.winner!].name} 获胜</h2><div className="scoreboard">{game.players.map((p,i)=><div key={i} className={i===game.winner?'winner':''}><SeatBadge seat={i}/><b>{p.name}</b><strong>{p.score}</strong></div>)}</div>{(local||room?.host===viewer)?<button className="primary" onClick={next} disabled={busy}>{game.matchWinner!==null?'再来一局':'下一局'}</button>:<p>等待房主开始下一局</p>}</div>}
 </>}
 </section>
 {game&&game.phase!=='over'&&<section className="hand-dock" aria-label="手牌区域"><div className="hand-toolbar"><div className="hand-owner"><SeatBadge seat={viewer}/><b>{my!.name}</b><span>{my!.count} 张</span></div><div className="hand-controls">{mode==='flex'&&<button className={`flex-toggle ${useFlex?'armed':''}`} disabled={!myTurn||!my!.power||busy} onClick={()=>setUseFlex(!useFlex)}><Zap size={17}/>{useFlex?'强化已就绪':'FLEX 强化'}</button>}<button className={`uno-button ${my!.called?'called':''}`} disabled={busy||(!!local&&masked)||!(my!.count===1||(myTurn&&my!.count===2))} onClick={()=>act({type:'uno'})}>UNO!</button>{game.unoVulnerable!==null&&game.unoVulnerable!==viewer&&<button className="catch-button" disabled={busy||(!!local&&masked)} onClick={()=>act({type:'catch'})}>举报漏喊</button>}{game.pending&&myTurn&&<><button className="danger-button" disabled={busy} onClick={()=>act({type:'accept'})}>接受 {game.pending.kind==='wildColor'?'抽色':`+${game.pending.amount}`}</button>{game.pending.challenge&&<button className="ghost" disabled={busy} onClick={()=>act({type:'challenge'})}>质疑</button>}</>}{game.drawn&&myTurn?<button className="ghost" disabled={busy} onClick={()=>act({type:'pass'})}>过牌</button>:!game.pending&&<button className="ghost" disabled={!myTurn||busy||game.phase==='color'} onClick={()=>act({type:'draw'})}>摸一张</button>}</div></div>
 {(!!local&&masked)?<div className="hidden-hand"><Shield size={22}/> 手牌已隐藏</div>:<div className={`hand-cards ${useFlex?'flex-armed':''}`}>{my!.hand.map((c,i)=>{const legal=game.legal.find(l=>l.id===c.id);const playable=!!(useFlex?legal?.flex:legal?.normal);return <PlayingCard key={c.id} card={c} side={game.side} playable={playable} selected={game.drawn===c.id} disabled={!myTurn||busy||!playable} onClick={()=>play(c)} style={{'--i':i,'--count':my!.hand.length} as CSSProperties}/>})}</div>}
 <div className="hand-hint">{local&&masked?'接手后显示自己的牌':useFlex?'亮框牌可强化 · 副色只用于匹配，出牌后跟主色':game.drawn?'只有刚摸到的牌可以出，或点击过牌':'点击亮框牌出牌 · 剩两张时可预先喊 UNO'}</div></section>}
 </div>
 {activeFx&&<div key={activeFx.id} className={`screen-fx fx-${activeFx.type}`} aria-hidden="true"><div className="fx-ring"/>{activeFx.cameo!==undefined&&<div className={`cameo-burst cameo-${activeFx.cameo}`}><CameoArt cameo={activeFx.cameo}/><b>✦ {CAMEOS[activeFx.cameo]}</b></div>}<div className="fx-caption">{({flip:game?.side?'DARK SIDE':'LIGHT SIDE',flex:'FLEX!',stack:`STACK +${activeFx.amount}`,damage:`+${activeFx.amount}`,uno:'UNO!',reverse:'REVERSE',win:'VICTORY',attack:`+${activeFx.amount}`,play:''} as Record<string,string>)[activeFx.type]}</div>{Array.from({length:12},(_,i)=><i key={i} style={{'--n':i} as CSSProperties}/>)}</div>}
 <Dialog open={!!modal} onOpenChange={o=>!o&&setModal(null)}><DialogContent className={`game-dialog ${modal==='rules'?'rules-dialog':''}`}><DialogTitle>{({online:'在线四人房间',local:'同屏四人',rules:`${TITLES[mode]} · 规则`,settings:'偏好设置',log:'对局记录',eggs:'卡牌彩蛋',leave:'离开牌桌'} as Record<string,string>)[modal??'']}</DialogTitle><DialogDescription>{({online:'创建房间，把邀请链接发给另外三位玩家。',local:'同一台设备轮流操作，交接时自动隐藏手牌。',rules:'官方机制与可选房规分别说明。',settings:'根据你的习惯调整反馈强度。',eggs:'四人藏在数字 7 中；点击卡牌预览特效。',log:'最近的出牌与效果。',leave:game&&room?'线上座位会保留，可通过同一浏览器重连。':'离开后可重新创建或加入牌局。'} as Record<string,string>)[modal??'']}</DialogDescription>
 {modal==='online'&&<><label>你的昵称<input value={name} onChange={e=>setName(e.target.value)} maxLength={16} placeholder="输入昵称" autoComplete="nickname"/></label><Tabs value={tab} onValueChange={setTab}><TabsList className="room-tabs"><TabsTrigger value="create">创建房间</TabsTrigger><TabsTrigger value="join">加入房间</TabsTrigger></TabsList><TabsContent value="create"><div className="option-row"><span>加牌叠加 <small>同类加牌接力 · 自定义房规</small></span><Switch aria-label="加牌叠加" checked={stacking} onCheckedChange={setStacking}/></div><div className="option-row"><span>500 分赛 <small>关闭时为单局胜负</small></span><Switch aria-label="500 分赛" checked={match500} onCheckedChange={setMatch500}/></div><button className="primary full" disabled={busy||!name.trim()} onClick={()=>roomOp('create',{mode,name,stacking,match500})}>{busy?'创建中…':'创建四人房间'}</button></TabsContent><TabsContent value="join"><label>房间号<input aria-label="房间号" value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,'').slice(0,6))} placeholder="6 位房间号" maxLength={6}/></label><button className="primary full" disabled={busy||!name.trim()||joinCode.length!==6} onClick={()=>roomOp('join',{code:joinCode,mode,name})}>{busy?'加入中…':'入座'}</button></TabsContent></Tabs></>}
 {modal==='local'&&<><div className="local-names">{names.map((n,i)=><label key={i}><SeatBadge seat={i}/><input aria-label={`玩家 ${i+1} 昵称`} value={n} maxLength={16} onChange={e=>setNames(old=>old.map((x,j)=>j===i?e.target.value:x))}/></label>)}</div><div className="option-row"><span>加牌叠加 <small>同类加牌接力 · 自定义房规</small></span><Switch aria-label="加牌叠加" checked={stacking} onCheckedChange={setStacking}/></div><div className="option-row"><span>500 分赛</span><Switch aria-label="500 分赛" checked={match500} onCheckedChange={setMatch500}/></div><button className="primary full" onClick={startLocal}>开始对局</button></>}
 {modal==='rules'&&<Rules mode={mode}/>} {modal==='eggs'&&<EggGallery mode={mode} onPreview={cameo=>{setFx({id:Date.now(),type:'play',text:'彩蛋预览',cameo});tone('play')}}/>}
 {modal==='settings'&&<><div className="option-row"><span>音效</span><Switch aria-label="音效" checked={sound} onCheckedChange={v=>prefs('sound',v)}/></div><div className="option-row"><span>战斗特效 <small>震屏、红屏、翻面与强化动画</small></span><Switch aria-label="战斗特效" checked={effects} onCheckedChange={v=>prefs('effects',v)}/></div><button className="secondary" onClick={()=>{setModal(null);const type=mode==='flip'?'flip':mode==='flex'?'flex':'stack';setFx({id:Date.now(),type,text:'效果预览',amount:8});tone(type)}}>预览特效</button><button className="secondary" onClick={()=>setModal('eggs')}>卡牌彩蛋</button><button className="text-button" onClick={()=>setModal('rules')}>规则与素材来源</button></>}
 {modal==='log'&&game&&<>{game.reveal&&<div className="challenge-proof"><h3>质疑时的手牌证据</h3><div>{game.reveal.map((f,i)=><span key={i}>{label(f)}</span>)}</div></div>}{mode==='flip'&&game.players.filter((_,i)=>i!==viewer).map(p=><div className="back-list" key={p.name}><h3>{p.name} · 背面</h3><div>{p.backs.map((f,i)=><PlayingCard key={i} card={{id:`back${i}`,a:f}} small/>)}</div></div>)}<ol className="event-log">{[...game.events].reverse().map(e=><li key={e.id}><span>{String(e.id).padStart(2,'0')}</span>{e.text}</li>)}</ol></>}
 {modal==='leave'&&<div className="dialog-actions"><button className="secondary" onClick={()=>setModal(null)}>继续玩</button><button className="primary" onClick={leave}>离开牌桌</button></div>}
 </DialogContent></Dialog>
 <Dialog open={!!pick||(!!game&&game.phase==='color'&&myTurn)} onOpenChange={o=>{if(!o)setPick(null)}}><DialogContent className="game-dialog" showCloseButton={game?.phase!=='color'}><DialogTitle>{needTarget?'选择目标与颜色':'选择颜色'}</DialogTitle><DialogDescription>{needTarget?'指定对手承受加牌，下一家照常行动。':'选择接下来跟随的颜色。'}</DialogDescription>{needTarget&&<div className="target-picker">{game!.players.map((p,i)=>i!==viewer&&<button key={i} className={target===i?'active':''} onClick={()=>setTarget(i)}><SeatBadge seat={i}/>{p.name}</button>)}</div>}<div className="color-picker">{colors(game??{mode,side:0}).map(c=><button className={`color-${c} ${chosen===c?'chosen':''}`} key={c} aria-label={`选择${COLOR_NAMES[c]}色`} onClick={()=>setChosen(c)}>{symbols[c]} {COLOR_NAMES[c]}{chosen===c&&<Check size={18}/>}</button>)}</div><button className="primary full" disabled={!chosen||busy||!!(needTarget&&target===null)} onClick={()=>act(pick?{type:'play',id:pick.card.id,flex:pick.flex,color:chosen!,...(target!==null?{target}:{})}:{type:'color',color:chosen!})}>确认出牌</button></DialogContent></Dialog>
 </main>
}


