"use client";
/* eslint-disable @next/next/no-html-link-for-pages -- Full page navigation isolates each table and its saved session. */
import {Fragment,useEffect,useRef,useState} from 'react';
import type {CSSProperties} from 'react';
import {Gamepad2,Layers,BookOpen,Volume2,VolumeX,Settings2,Wifi,Monitor,Zap,Rotate3d,Copy,LogOut,History,Eye,Shield,Check,RefreshCw,Flag,PanelTopClose,PanelTopOpen,Ban,RotateCw,RotateCcw} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {nextRound,applyAction,viewGame,face,label,colors,COLOR_NAMES,type Mode,type Game,type GameView,type Card,type Action,type Color,type Event} from '@/lib/game';
import {PlayingCard,SeatBadge,CameoArt,CAMEOS,EggGallery} from './cards';
import Rules from './rules';
import Hand from './hand';
import {cardEffect} from '@/lib/card-effects';
import {useRoomSync} from './use-room-sync';
type Room={code:string;mode:Mode;playMode:'online'|'shared';seats:({name:string;avatar:number;ready:boolean;virtual:boolean;online:boolean}|null)[];host:number;viewer:number;revision:number;stacking:boolean;match500:boolean;jumpIn:boolean;finishMode:'first'|'ranking';game:GameView|null};
type Modal='online'|'local'|'rules'|'settings'|'log'|'leave'|'eggs'|'invite'|'backs'|null;
const NAMES=['玩家 1','玩家 2','玩家 3','玩家 4'];
const requestId=()=>Array.from(crypto.getRandomValues(new Uint8Array(16)),x=>x.toString(16).padStart(2,'0')).join('');
const TITLES={classic:'经典 UNO',flip:'UNO FLIP',flex:'UNO FLEX'};
const ROUTES={classic:'/',flip:'/flip',flex:'/flex'};
const symbols:Record<Color,string>={red:'●',yellow:'◆',green:'▲',blue:'■',pink:'●',teal:'◆',orange:'▲',purple:'■',wild:'✦'};
export default function Arcade({mode}:{mode:Mode}){
 const [modal,setModal]=useState<Modal>(null),[tab,setTab]=useState('create');
 const [navHidden,setNavHidden]=useState(false),[backSeat,setBackSeat]=useState(0),[backIndex,setBackIndex]=useState(0);
 const [inviteUrl,setInviteUrl]=useState('');
 const [resumeCode,setResumeCode]=useState('');
 const [names,setNames]=useState([...NAMES]),[name,setName]=useState(''),[joinCode,setJoinCode]=useState('');
 const [stacking,setStacking]=useState(false),[match500,setMatch500]=useState(false),[jumpIn,setJumpIn]=useState(false),[finishMode,setFinishMode]=useState<'first'|'ranking'>('first');
 const [room,setRoom]=useState<Room|null>(null),[local,setLocal]=useState<Game|null>(null),[masked,setMasked]=useState(true);
 const [busy,setBusy]=useState(false),[connected,setConnected]=useState(true),[useFlex,setUseFlex]=useState(false);
 const [pick,setPick]=useState<{card:Card;flex:boolean}|null>(null),[chosen,setChosen]=useState<Color|null>(null),[target,setTarget]=useState<number|null>(null);
 const [sound,setSound]=useState(false),[effects,setEffects]=useState(true),[fx,setFx]=useState<Event|null>(null),[fxQueue,setFxQueue]=useState<Event[]>([]),[seatEffects,setSeatEffects]=useState<Event[]>([]);
 const [touchTapToPlay,setTouchTapToPlay]=useState(false),[cardShine,setCardShine]=useState(false),[showCameo,setShowCameo]=useState(false),[inspectScope,setInspectScope]=useState<string|null>(null);
 const token=useRef(''),roomRef=useRef<Room|null>(null),fxBaseline=useRef<{table:string;round:number;id:number}|null>(null),wasDisconnected=useRef(false),audio=useRef<AudioContext|null>(null),pendingOp=useRef(false);
 const game=local?viewGame(local,local.turn):room?.game??null;
 const isHost=!!room&&room.viewer===room.host;
 const shared=!!local||room?.playMode==='shared'&&isHost;
 const spectating=room?.playMode==='shared'&&!isHost;
 const viewer=local?local.turn:shared&&game?game.turn:room?.viewer??0;
 const myTurn=!!game&&game.turn===viewer&&game.phase!=='over'&&!spectating&&(!shared||!masked)&&!(room?.playMode==='online'&&room.seats[game.turn]?.virtual);
 const inspectionKey=`${mode}-${room?.code??'local'}-${viewer}-${game?.round}-${game?.side}`;
 const inspectOther=inspectScope===inspectionKey&&mode==='flip'&&!spectating&&(!shared||!masked);
 const my=game?.players[viewer];
 const offlineTurn=!!room&&room.playMode==='online'&&!!game&&game.phase!=='over'&&!room.seats[game.turn]?.virtual&&room.seats[game.turn]?.online===false;
 const receive=(r:Room)=>{if(wasDisconnected.current&&r.game){fxBaseline.current={table:r.code,round:r.game.round,id:r.game.events.at(-1)?.id??0};wasDisconnected.current=false;setFxQueue([]);setSeatEffects([]);setFx(null)}if(!roomRef.current||r.code!==roomRef.current.code||r.revision>=roomRef.current.revision){const prev=roomRef.current;if(!prev||prev.code!==r.code||prev.playMode!==r.playMode||prev.game?.turn!==r.game?.turn||prev.game?.round!==r.game?.round||prev.game?.side!==r.game?.side){setInspectScope(null);setPick(null)}if(r.playMode==='shared'&&r.viewer===r.host&&(!prev||prev.playMode!==r.playMode||prev.game?.turn!==r.game?.turn||prev.game?.round!==r.game?.round)){setMasked(true);setModal(m=>m==='backs'?null:m)}if(prev?.playMode!==r.playMode){setPick(null);setUseFlex(false)}roomRef.current=r;setRoom(r)}setConnected(true)};
 async function refresh(code:string,t=token.current){const response=await fetch(`/api/room?code=${code}`,{headers:{Authorization:`Bearer ${t}`},cache:'no-store',signal:AbortSignal.timeout(8000)});const data=await response.json() as Room & {error?:string;token?:string;left?:boolean};if(!response.ok)throw Error(data.error);if(data.mode===mode)receive(data);return data as Room}
 useEffect(()=>{
  const frame=requestAnimationFrame(()=>{
  try{const prefs=JSON.parse(localStorage.getItem('uno-prefs')??'{}');setNavHidden(prefs.navHidden??false);setSound(prefs.sound??false);setEffects(prefs.effects??!matchMedia('(prefers-reduced-motion: reduce)').matches);setTouchTapToPlay(prefs.touchTapToPlay??false);setCardShine(prefs.cardShine??false);setShowCameo(prefs.showCameo??false);setResumeCode(localStorage.getItem(`uno-last-room-${mode}`)??'');
   const c=new URLSearchParams(location.search).get('room');
   if(c){setJoinCode(c.toUpperCase());const saved=JSON.parse(sessionStorage.getItem(`uno-room-${c}`)??localStorage.getItem(`uno-room-${c}`)??'null');if(saved?.token){token.current=saved.token;rememberRoom(c);refresh(c,saved.token).catch(()=>{setModal('online');setTab('join');toast.error('重连失败，请检查房间号或重新入座')})}else{setModal('online');setTab('join')}}
   else{const saved=JSON.parse(localStorage.getItem(`uno-local-${mode}`)??'null');if(saved?.players?.length===4&&saved.mode===mode){if(saved.players.every((p:{name:string},i:number)=>p.name===CAMEOS[i]))saved.players.forEach((p:{name:string},i:number)=>{p.name=NAMES[i]});if(saved.players.every((p:{name:string},i:number)=>p.name===NAMES[i]))saved.events.forEach((e:Event)=>{e.text=CAMEOS.slice(0,4).reduce((text,n,i)=>text.replaceAll(n,NAMES[i]),e.text)});setLocal(saved);setMasked(true)}}
  }catch{/* Ignore invalid device-local preferences. */}
  });return()=>cancelAnimationFrame(frame);
 // Restore once for each table; later polling uses the current callbacks.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[mode]);
 useEffect(()=>{if(local)try{localStorage.setItem(`uno-local-${mode}`,JSON.stringify(local))}catch{}},[local,mode]);
 useRoomSync(room?.code,token,roomRef,receive,value=>{if(!value)wasDisconnected.current=true;setConnected(value)});
 function tone(type:string){if(!sound)return;try{const ctx=audio.current??new AudioContext();audio.current=ctx;void ctx.resume();const osc=ctx.createOscillator(),gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.type=['damage','stack'].includes(type)?'sawtooth':'triangle';const freq=type==='flip'?240:type==='flex'?600:type==='damage'?100:440;osc.frequency.setValueAtTime(freq,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(type==='damage'?40:freq*1.8,ctx.currentTime+.18);gain.gain.setValueAtTime(.055,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.3);osc.start();osc.stop(ctx.currentTime+.31)}catch{}}
 useEffect(()=>{
  if(!game){fxBaseline.current=null;return}
  const table=room?.code??`local-${mode}`,last=game.events.at(-1)?.id??0,baseline=fxBaseline.current;
  fxBaseline.current={table,round:game.round,id:last};
  if(!baseline||baseline.table!==table||baseline.round!==game.round||wasDisconnected.current){wasDisconnected.current=false;queueMicrotask(()=>{setFxQueue([]);setSeatEffects([]);setFx(null)});return}
  const batch=game.events.filter(e=>e.id>baseline.id),queue:Event[]=[];
  for(const e of batch){
   if(e.type==='play'){if(showCameo&&e.cameo!==undefined)queue.push(e);continue}
   if(e.type==='win')continue;
   if((effects&&['flip','flex','stack','damage','uno','reverse','attack','skip','color','finish'].includes(e.type))||['damage','skip','finish'].includes(e.type))queue.push({...e,cameo:undefined});
  }
  if(batch.length)queueMicrotask(()=>{if(queue.length)setFxQueue(old=>[...old,...queue]);setUseFlex(false)});
 // Events are already projected for this seat. Keep a baseline across reconnects.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[game?.revision,game?.round,room?.code]);
 useEffect(()=>{if(fx||!fxQueue.length)return;const frame=requestAnimationFrame(()=>{setFx(fxQueue[0]);setFxQueue(old=>old.slice(1))});return()=>cancelAnimationFrame(frame)},[fx,fxQueue]);
 useEffect(()=>{
  if(!fx)return;
  const frame=requestAnimationFrame(()=>{
   if(effects&&['stack','attack','damage','skip','finish'].includes(fx.type))setSeatEffects(old=>[...old.filter(e=>e.id!==fx.id),fx]);
   if(['damage','skip','finish'].includes(fx.type))toast(fx.text,{duration:2800});
   if(activeFx)tone(fx.type);
  });
  const t=setTimeout(()=>setFx(null),fx.type==='flip'?1500:fx.type==='finish'?1400:950);
  return()=>{cancelAnimationFrame(frame);clearTimeout(t)};
 // Audio and seat feedback follow the displayed event, including UNO before its card effect.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[fx]);
 useEffect(()=>{if(!seatEffects.length)return;const t=setTimeout(()=>setSeatEffects([]),2200);return()=>clearTimeout(t)},[seatEffects]);
 async function roomOp(op:string,extra:Record<string,unknown>={}){
  if(pendingOp.current)return;pendingOp.current=true;setBusy(true);try{const current=roomRef.current;const response=await fetch('/api/room',{method:'POST',headers:{'Content-Type':'application/json',...(token.current?{Authorization:`Bearer ${token.current}`}:{})},body:JSON.stringify({op,code:current?.code,revision:current?.revision,requestId:requestId(),...extra}),signal:AbortSignal.timeout(8000)});const data=await response.json() as Room & {error?:string;token?:string;left?:boolean};if(!response.ok){if(response.status===409&&current)await refresh(current.code);if(data.mode&&data.mode!==mode){location.href=`${ROUTES[data.mode as Mode]}?room=${encodeURIComponent(joinCode.toUpperCase())}`;return}throw Error(data.error??'操作失败，请重试')}
   if(data.token){setLocal(null);localStorage.removeItem(`uno-local-${mode}`);token.current=data.token;sessionStorage.setItem(`uno-room-${data.code}`,JSON.stringify({token:data.token}));localStorage.setItem(`uno-room-${data.code}`,JSON.stringify({token:data.token}));rememberRoom(data.code);history.replaceState(null,'',`${ROUTES[mode]}?room=${data.code}`)}
   if(data.left){sessionStorage.removeItem(`uno-room-${current?.code}`);localStorage.removeItem(`uno-room-${current?.code}`);localStorage.removeItem(`uno-last-room-${mode}`);setResumeCode('');token.current='';roomRef.current=null;setRoom(null);history.replaceState(null,'',ROUTES[mode])}else receive(data);
   setModal(null);return data;
  }catch(e){toast.error(e instanceof Error?e.message:'连接失败，请重试')}finally{pendingOp.current=false;setBusy(false)}
 }
 async function act(action:Action){
  if(busy||inspectOther)return;try{if(local){const updated=applyAction(local,viewer,action);setLocal(updated);if(updated.turn!==local.turn||updated.side!==local.side||updated.round!==local.round)setInspectScope(null);if(updated.turn!==local.turn&&updated.phase!=='over'){setMasked(true);setModal(m=>m==='backs'?null:m)}}else await roomOp('action',{action});setPick(null);setUseFlex(false)}catch(e){toast.error(e instanceof Error?e.message:'无法操作')}
 }
 function startLocal(){if(names.some(n=>!n.trim())){toast.error('请填写四位玩家的昵称');return}fxBaseline.current=null;setMasked(true);void roomOp('create',{mode,name:names[0],names,playMode:'shared',stacking,match500:finishMode==='first'&&match500,jumpIn,finishMode})}
 function switchDevice(playMode:'online'|'shared'){if(room){if(isHost&&room.playMode!==playMode)void roomOp('mode',{playMode})}else{setTab('create');setModal(playMode==='online'?'online':'local')}}
 function play(card:Card){if(!game||busy||inspectOther||spectating||shared&&masked)return;const f=face(card,game!.side);const flex=!!(useFlex&&f.flex&&my?.power);const legal=game!.legal.find(l=>l.id===card.id);if(!(flex?legal?.flex:legal?.normal))return;if(f.color==='wild'){setPick({card,flex});setChosen(null);setTarget(null)}else void act({type:'play',id:card.id,flex})}
 function next(){setInspectScope(null);fxBaseline.current=null;if(local){setLocal(nextRound(local));setMasked(true)}else void roomOp('next')}
 async function invite(){if(!room)return;let origin=location.origin;try{const info=await fetch('/api/connection').then(r=>r.json()) as {lanOrigin?:string};if(info.lanOrigin&&['localhost','127.0.0.1'].includes(location.hostname))origin=info.lanOrigin}catch{}const url=`${origin}${ROUTES[mode]}?room=${room.code}`;setInviteUrl(url);setModal('invite');try{await navigator.clipboard.writeText(url);toast.success('邀请链接已复制')}catch{}}
 function rememberRoom(code:string){localStorage.setItem(`uno-last-room-${mode}`,code);setResumeCode(code)}
 function savedToken(code:string){try{return JSON.parse(sessionStorage.getItem(`uno-room-${code}`)??localStorage.getItem(`uno-room-${code}`)??'null')?.token as string|undefined}catch{return undefined}}
 async function resume(code:string){
  if(pendingOp.current)return;const saved=savedToken(code);if(!saved){toast.error('此浏览器没有该座位的记录，请使用原浏览器返回');return}
  pendingOp.current=true;setBusy(true);
  try{token.current=saved;const restored=await refresh(code,saved);if(restored.mode!==mode){location.href=`${ROUTES[restored.mode]}?room=${code}`;return}rememberRoom(code);setLocal(null);setModal(null);history.replaceState(null,'',`${ROUTES[mode]}?room=${code}`);fxBaseline.current=null}
  catch(e){toast.error(e instanceof Error?e.message:'重连失败，请稍后重试')}
  finally{pendingOp.current=false;setBusy(false)}
 }
 function join(){if(savedToken(joinCode)){void resume(joinCode)}else void roomOp('join',{code:joinCode,mode,name})}
 function leave(){if(pendingOp.current)return;setInspectScope(null);if(room&&!game){void roomOp('leave');return}if(local){localStorage.removeItem(`uno-local-${mode}`);setLocal(null)}if(room){rememberRoom(room.code);roomRef.current=null;setRoom(null);history.replaceState(null,'',ROUTES[mode])}setModal(null);fxBaseline.current=null}
 function prefs(key:'sound'|'effects'|'touchTapToPlay'|'cardShine'|'navHidden'|'showCameo',value:boolean){
  const values={sound,effects,touchTapToPlay,cardShine,navHidden,showCameo,[key]:value};
  setSound(values.sound);setEffects(values.effects);setTouchTapToPlay(values.touchTapToPlay);setCardShine(values.cardShine);setNavHidden(values.navHidden);setShowCameo(values.showCameo);
  localStorage.setItem('uno-prefs',JSON.stringify(values));if(key==='sound'&&value){try{audio.current??=new AudioContext();void audio.current.resume()}catch{}}
 }
 function toggleNav(){prefs('navHidden',!navHidden)}
 const visibleRef=useRef<unknown>(null); visibleRef.current={mode,room:room?.code??null,game:shared&&masked?{turn:game?.turn,masked:true}:game};
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options?:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:'read_uno_table',description:'读取当前可见牌局、自己的手牌与可用动作，不暴露其他玩家手牌。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:Record<string,unknown>)=>{if(input&&Object.keys(input).length)throw Error('此工具不接受参数');return visibleRef.current}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
 const seats=game?.players??room?.seats??NAMES.map((n,i)=>({name:n,avatar:i,ready:false}));
 const needTarget=pick?.flex&&['target2','wild4'].includes(face(pick.card,game?.side).kind);
 const fxTargets=fx?.targets??(fx?.target===undefined?[]:[fx.target]);
 const targetedFx=!!fx&&['attack','damage','skip','finish'].includes(fx.type);
 const activeFx=fx&&(effects||fx.type==='play'&&showCameo)&&(!targetedFx||!spectating&&(shared||fxTargets.includes(room?.viewer??viewer)))?fx:null;
 const nextSeat=game&&game.phase!=='over'?Array.from({length:3},(_,n)=>(game.turn+(n+1)*game.dir+8)%4).find(i=>!game.rankings.includes(i))??null:null;
 const backFaces=game&&(!shared||!masked)?(backSeat===viewer?game.players[viewer].hand.map(c=>face(c,1-game.side)):game.players[backSeat].backs):[];
 const outcomeWinner=game?.matchWinner??game?.winner;
 const won=outcomeWinner===viewer;
 return <main className={`arcade mode-${mode} ${game?'in-game':''} ${navHidden?'nav-hidden':''} ${cardShine?'':'no-card-shine'} ${game?.side?'dark-side':''} ${activeFx&&['damage','stack'].includes(activeFx.type)?'shake':''}`}><Toaster theme="dark" position="top-center"/>
 <aside className="rail"><a className="brand-icon" href="/" aria-label="UNO CLUB"><Gamepad2/></a><div className="rail-line"/>{([['classic',Layers],['flip',Rotate3d],['flex',Zap]] as const).map(([m,Icon])=><a key={m} className={`rail-item ${m===mode?'selected':''}`} href={ROUTES[m]} title={TITLES[m]} aria-label={TITLES[m]}><Icon/></a>)}</aside>
 <div className="workspace"><header className="topbar" hidden={navHidden}><a className="wordmark" href="/">UNO <b>CLUB<span>+</span></b></a><nav>{(['classic','flip','flex'] as Mode[]).map(m=><a key={m} className={mode===m?'active':''} href={ROUTES[m]}>{TITLES[m]}{m==='flex'&&<Zap size={14}/>}</a>)}</nav><div className="header-tools"><button aria-label="隐藏导航栏" title="隐藏导航栏" onClick={toggleNav}><PanelTopClose size={19}/></button><button aria-label="游戏规则" title="游戏规则" onClick={()=>setModal('rules')}><BookOpen size={19}/></button><button aria-label={sound?'关闭声音':'开启声音'} title={sound?'关闭声音':'开启声音'} onClick={()=>prefs('sound',!sound)}>{sound?<Volume2 size={19}/>:<VolumeX size={19}/>}</button><button aria-label="设置" title="设置" onClick={()=>setModal('settings')}><Settings2 size={19}/></button></div></header>
 <div className="room-strip"><div className="room-info"><h1>{room?`房间 ${room.code}`:local?'同屏四人':TITLES[mode]}</h1>{game&&<span className="tag">第 {game.round} 局</span>}{(game?.stacking??room?.stacking)&&<span className="rule-chip">叠加房规</span>}{room&&<span className={connected?'connection-status':'disconnect'}>{connected?'已连接':'连接中断 · 正在重连'}</span>}</div><div className="room-controls">{offlineTurn&&isHost&&<button className="danger-button skip-offline" disabled={busy||inspectOther} onClick={()=>roomOp('skipOffline')}>跳过离线玩家</button>}{navHidden&&<button className="icon-button" aria-label="显示导航栏" title="显示导航栏" onClick={toggleNav}><PanelTopOpen size={18}/></button>}<div className="device-mode" role="group" aria-label="设备模式"><button aria-pressed={!shared&&room?.playMode!=='shared'} disabled={busy||!!room&&!isHost} onClick={()=>switchDevice('online')} title="四台设备各自操作"><Wifi size={14}/><span>四设备</span></button><button aria-pressed={shared||room?.playMode==='shared'} disabled={busy||!!room&&!isHost} onClick={()=>switchDevice('shared')} title="单设备轮流操作四位玩家"><Monitor size={14}/><span>单设备</span></button></div>{room&&<button className="ghost" onClick={invite}><Copy size={15}/><span>邀请</span></button>}{game&&<button className="icon-button" aria-label="对局记录" onClick={()=>setModal('log')}><History size={18}/></button>}{(room||local)&&<button className="icon-button" aria-label="离开牌桌" onClick={()=>setModal('leave')}><LogOut size={18}/></button>}</div></div>
 <section className={`table-stage ${game?`table-color-${game.color} ${myTurn?'table-your-turn':'table-waiting'}`:''}`}><div className="table-grid"/><div className="orbit orbit-one"/><div className="orbit orbit-two"/>
 {seats.map((s,i)=><div className={`seat seat-${i} ${game?`relative-seat relative-${(i-viewer+4)%4}`:''} ${game&&game.turn===i&&game.phase!=='over'?'current':''} ${game&&game.unoVulnerable===i?'vulnerable':''} ${game?.rankings?.includes(i)?'finished-seat':''} ${game&&game.rankings.includes(i)&&game.rankings.indexOf(i)<3&&game.players[i].count===0?'victorious-seat':''} ${nextSeat===i?'next-seat':''} ${game?.pending?.target===i?'pending-target':''} ${effects&&seatEffects.some(e=>(e.targets??(e.target===undefined?[]:[e.target])).includes(i))?'seat-impacted':''}`} key={i}><SeatBadge seat={i}/><div className="seat-info"><b>{s?.name??'空座位'}<small>{(room&&!shared&&viewer===i)?'你':`P${i+1}`}</small></b><span>{game?<><strong>{game.players[i].count}</strong> 张{room?.playMode==='online'&&room.seats[i]?.virtual&&<em className="waiting-device">待加入</em>}{game.mode==='flex'&&<em className={game.players[i].power?'charged':'empty'}>{game.players[i].power?'⚡ 可强化':'× 已耗尽'}</em>}</>:room?(s?(room?.seats[i]?.ready?'已准备':'未准备'):'等待加入'):'等待入座'}</span>{game&&<small className="seat-score">{game.players[i].score} 分 {game.players[i].called&&<mark>UNO!</mark>}</small>}</div>{room&&room.seats[i]&&<span className={`seat-presence ${room.seats[i]!.online?'online':'offline'}`}>{room.seats[i]!.virtual?(room.playMode==='shared'?'本机操作':'待加入'):room.seats[i]!.online?'在线':'离线'}</span>}{game&&game.turn===i&&game.phase!=='over'&&<span className="turn-seat-label">出牌中</span>}{nextSeat===i&&<span className="next-seat-label">下家</span>}{game?.rankings?.includes(i)&&(game.rankings.indexOf(i)<3&&game.players[i].count===0?<span className="seat-finish-status"><Flag size={11}/><strong>VICTORY</strong><b>第 {game.rankings.indexOf(i)+1} 名</b></span>:<span className="seat-rank">第 {game.rankings.indexOf(i)+1} 名</span>)}{effects&&seatEffects.filter(e=>(e.targets??(e.target===undefined?[]:[e.target])).includes(i)).map(e=><Fragment key={e.id}><span className={`seat-impact-visual seat-impact-${e.type}`} data-event-type={e.type} data-event-id={e.id} aria-hidden="true"><span className="seat-fx-ring"/><span className="seat-fx-ring seat-fx-ring-secondary"/><span className="seat-fx-icon">{e.type==='skip'?<Ban/>:e.type==='finish'?<Flag/>:e.type==='stack'?<Layers/>:<Zap/>}</span>{Array.from({length:8},(_,n)=><i key={n} className="seat-fx-particle" style={{'--n':n} as CSSProperties}/>)}</span><span className={`seat-effect seat-effect-${e.type}`} role="status"><b>{e.type==='finish'?`VICTORY · 第 ${e.rank??game!.rankings.indexOf(i)+1} 名`:e.type==='skip'?'SKIP':e.type==='stack'?`STACK +${e.amount}`:`+${e.amount}`}</b><small>{e.type==='damage'?`摸 ${e.amount} 张`:e.type==='attack'||e.type==='stack'?'接招':e.type==='finish'?'手牌已出完':'本次回合跳过'}</small></span></Fragment>)}{room&&!game&&room.seats[i]?.ready&&<Check className="ready-check" size={16}/>}</div>)}
 {!game&&!room&&<div className="center-start"><div className={`uno-title title-${mode}`}>UNO<span>{mode==='classic'?'!':mode.toUpperCase()}</span></div><div className="start-actions"><button className="primary" onClick={()=>{setModal('online');setTab('create')}}><Wifi size={18}/> 四台设备</button><button className="secondary" onClick={()=>setModal('local')}><Monitor size={18}/> 单设备四人</button></div>{resumeCode&&<button className="secondary resume-table" disabled={busy} onClick={()=>resume(resumeCode)}><RefreshCw size={17}/> 返回牌桌 {resumeCode}</button>}<button className="text-button" onClick={()=>setModal('rules')}>玩法说明</button></div>}
 {room&&!game&&<div className="center-start lobby-center"><div className="lobby-count">{room.seats.filter(Boolean).length}<span> / 4</span></div><h2>{room.playMode==='shared'?'单设备四人':'等待玩家入座'}</h2><p className="room-code">{room.code}</p><div className="start-actions"><button className="secondary" onClick={invite}><Copy size={17}/> 复制邀请</button>{room.playMode!=='shared'&&<button className="primary" disabled={busy} onClick={()=>roomOp('ready',{ready:!room.seats[viewer]?.ready})}>{room.seats[viewer]?.ready?'取消准备':'我准备好了'}</button>}</div>{room.host===viewer&&<button className="start-game-button" disabled={busy||(room.playMode!=='shared'&&room.seats.some(s=>!s||!s.ready))} onClick={()=>roomOp('start')}>{room.playMode==='shared'?'开始轮流操作':'四人开局'}</button>}<p className="lobby-note">{room.playMode==='shared'?'房主设备轮流操作，交接隐藏手牌':'四人全部准备后，由房主开始'}</p></div>}
 {game&&<><div className="game-center"><div className="table-state"><span className={`color-indicator color-${game.color}`}>{symbols[game.color]} {COLOR_NAMES[game.color]}色</span><span className={`direction-status dir-${game.dir===1?'clockwise':'counterclockwise'}`} data-direction={game.dir} aria-label={game.dir===1?'顺时针出牌':'逆时针出牌'}>{game.dir===1?<RotateCw size={15} className="direction-arrow"/>:<RotateCcw size={15} className="direction-arrow"/>}{game.dir===1?'顺时针':'逆时针'}</span>{mode==='flip'&&<span className="side-label">{game.side?'暗面':'明面'}</span>}</div><div className="piles"><button className="draw-pile" aria-label={game.pending?'接受加牌':'摸一张牌'} disabled={inspectOther||!myTurn||busy||!!game.drawn||game.phase==='color'} onClick={()=>act({type:game.pending?'accept':'draw'})}><span>UNO</span><small>{game.deckCount} 张</small></button><div className="discard-wrap" key={`${game.top.id}-${game.side}`}><PlayingCard card={game.top} side={game.side}/><span className="pile-label">弃牌堆</span></div></div>{game.pending&&<div className="pending-badge">{game.pending.kind==='wildColor'?`抽至${COLOR_NAMES[game.pending.color!]}色`:`累计 +${game.pending.amount}`}<small>{game.players[game.pending.target].name} 接招</small></div>}<div className="turn-message" role="status">{game.phase==='over'?'本局结束':offlineTurn?`${game.players[game.turn].name} 已离线，${isHost?'可等待重连或跳过':'等待房主处理'}`:spectating?'单设备模式 · 请在房主设备轮流操作':shared&&masked?'等待交接':myTurn?(game.pending?'接牌，或接受惩罚':game.drawn?'打出刚摸的牌，或过牌':game.phase==='color'?'请选择颜色':'轮到你出牌'): `等待 ${game.players[game.turn].name} 出牌`}</div></div>
 {mode==='flip'&&!spectating&&(!shared||!masked)&&game.players.map((p,i)=>i!==viewer&&<button key={i} className={`opponent-backs backs-${(i-viewer+4)%4}`} aria-label={`查看 ${p.name} 的反面牌，共 ${p.backs.length} 张`} onClick={()=>{setBackSeat(i);setBackIndex(0);setModal('backs')}}><div className="back-fan" style={{'--count':Math.max(1,p.backs.length)} as CSSProperties}>{p.backs.map((f,j)=><PlayingCard key={j} small card={{id:`back-${i}-${j}`,a:f}} style={{'--i':j} as CSSProperties}/>)}</div><span><Eye size={11}/> {p.backs.length} 张反面</span></button>)}
 <div className="last-action">{game.events.at(-1)?.text}</div>
 {shared&&masked&&game.phase!=='over'&&<div className="handoff"><SeatBadge seat={viewer}/><Shield size={22}/><h2>交给 {game.players[viewer].name}</h2><p>请其他玩家移开视线</p><button className="primary" onClick={()=>setMasked(false)}><Eye size={17}/> 我已接手，查看手牌</button></div>}
 {game.phase==='over'&&<div className={`victory-panel ${!shared&&!won?'lose-panel':''}`}><Flag size={28}/><span>{game.finishMode==='ranking'?'RANKING':shared||spectating?'本局结束':won?'VICTORY':'LOSE'}</span><h2>{game.finishMode==='ranking'?'最终名次':`${game.players[outcomeWinner!].name} 获胜`}</h2>{game.finishMode!=='ranking'&&!shared&&!spectating&&<p className="round-result">{won?`本局获得 ${game.roundPoints.reduce((sum,n,i)=>i===game.winner?sum:sum+n,0)} 分`:`你的剩余手牌 ${game.roundPoints[viewer]??0} 分`}</p>}<div className={`scoreboard ${game.finishMode==='ranking'?'ranking-board':''}`}>{(game.finishMode==='ranking'?game.rankings:game.players.map((_,i)=>i)).map((i,rank)=><div key={i} className={i===game.winner?'winner':''}>{game.finishMode==='ranking'&&<span className="rank-number">第 {rank+1} 名</span>}<SeatBadge seat={i}/><b>{game.players[i].name}</b><strong>{game.finishMode==='ranking'?`${game.players[i].count} 张`:game.match500?`${game.players[i].score} 分`:i===game.winner?`+${game.roundPoints.reduce((sum,n)=>sum+n,0)} 分`:`${game.roundPoints[i]??0} 分`}</strong></div>)}</div>{(local||isHost)?<button className="primary" onClick={next} disabled={busy}>{game.matchWinner!==null?'再来一局':'下一局'}</button>:<p>等待房主开始下一局</p>}</div>}
 </>}
 </section>
 {game&&!spectating&&game.phase!=='over'&&<section className="hand-dock" aria-label="手牌区域"><div className="hand-toolbar"><div className="hand-owner"><SeatBadge seat={viewer}/><b>{my!.name}</b><span>{my!.count} 张</span></div><div className="hand-controls">{mode==='flip'&&(!shared||!masked)&&<button className="ghost own-backs" aria-label={inspectOther?'返回当前出牌面':'查看自己的另一面'} aria-pressed={inspectOther} disabled={busy} onClick={()=>{setPick(null);setInspectScope(inspectOther?null:inspectionKey)}}><Eye size={15}/> {inspectOther?'返回出牌面':'另一面'}</button>}{mode==='flex'&&<button className={`flex-toggle ${useFlex?'armed':''}`} disabled={inspectOther||!myTurn||!my!.power||busy} onClick={()=>setUseFlex(!useFlex)}><Zap size={17}/>{useFlex?'强化已就绪':'FLEX 强化'}</button>}<button className={`uno-button ${my!.called?'called':''}`} disabled={inspectOther||busy||(shared&&masked)||!(my!.count===1||((myTurn||game.legal.some(l=>l.jump))&&my!.count===2))} onClick={()=>act({type:'uno'})}>UNO!</button>{game.unoVulnerable!==null&&game.unoVulnerable!==viewer&&<button className="catch-button" disabled={inspectOther||busy||(shared&&masked)} onClick={()=>act({type:'catch'})}>举报漏喊</button>}{game.pending&&myTurn&&<><button className="danger-button" disabled={inspectOther||busy} onClick={()=>act({type:'accept'})}>接受 {game.pending.kind==='wildColor'?'抽色':`+${game.pending.amount}`}</button>{game.pending.challenge&&<button className="ghost" disabled={inspectOther||busy} onClick={()=>act({type:'challenge'})}>质疑</button>}</>}{game.drawn&&myTurn?<button className="ghost" disabled={inspectOther||busy} onClick={()=>act({type:'pass'})}>过牌</button>:!game.pending&&<button className="ghost" disabled={inspectOther||!myTurn||busy||game.phase==='color'} onClick={()=>act({type:'draw'})}>摸一张</button>}</div></div>
 {(shared&&masked)?<div className="hidden-hand"><Shield size={22}/> 手牌已隐藏</div>:<Hand key={`${game.round}-${viewer}-${game.side}`} game={game} viewer={viewer} armed={useFlex} busy={busy||inspectOther} inspectOther={inspectOther} touchTapToPlay={touchTapToPlay} onPlay={play}/>}
 </section>}
 </div>
 {activeFx&&<div key={activeFx.id} className={`screen-fx fx-${activeFx.type} ${activeFx.color?`fx-color-${activeFx.color}`:''}`} aria-hidden="true"><div className="fx-ring"/>{showCameo&&activeFx.cameo!==undefined&&<div className={`cameo-burst cameo-${activeFx.cameo}`}><CameoArt cameo={activeFx.cameo}/><b>✦ {CAMEOS[activeFx.cameo]}</b></div>}{['damage','attack','skip'].includes(activeFx.type)&&game&&<div className="fx-recipient">{(activeFx.targets??(activeFx.target===undefined?[]:[activeFx.target])).map(i=>game.players[i].name).join('、')}{activeFx.type==='damage'?` 摸 ${activeFx.amount} 张`:activeFx.type==='skip'?' 本次回合被跳过':' 接招'}</div>}{activeFx.type==='finish'&&<div className="fx-rank">第 {activeFx.rank??(activeFx.target===undefined?0:game!.rankings.indexOf(activeFx.target)+1)} 名</div>}{activeFx.type!=='color'&&<div className="fx-caption">{({flip:game?.side?'DARK SIDE':'LIGHT SIDE',flex:'FLEX!',stack:`STACK +${activeFx.amount}`,damage:`+${activeFx.amount}`,uno:'UNO!',reverse:'REVERSE',win:'',attack:`+${activeFx.amount}`,skip:'SKIP',finish:'VICTORY',color:'',play:''} as Record<string,string>)[activeFx.type]}</div>}{Array.from({length:12},(_,i)=><i key={i} style={{'--n':i} as CSSProperties}/>)}</div>}
 <Dialog open={!!modal} onOpenChange={o=>!o&&setModal(null)}><DialogContent className={`game-dialog ${modal==='rules'?'rules-dialog':''}`}><DialogTitle>{({online:'在线四人房间',local:'同屏四人',rules:`${TITLES[mode]} · 规则`,settings:'偏好设置',log:'对局记录',backs:game?`${game.players[backSeat].name} · ${backSeat===viewer?'当前未启用的一面':'反面牌'}`:'反面牌',eggs:'卡牌头像',invite:'邀请玩家',leave:'离开牌桌'} as Record<string,string>)[modal??'']}</DialogTitle><DialogDescription>{({online:'创建房间，把邀请链接发给另外三位玩家。',local:'同一台设备轮流操作，交接时自动隐藏手牌。',rules:'官方机制与可选房规分别说明。',settings:'根据你的习惯调整反馈强度。',eggs:mode==='flip'?'明面游戏开发部 · 暗面研讨会 · 万能 Kei。':mode==='flex'?'主色对应游戏开发部，副色用于强化匹配；万能 Kei。':'彩色牌游戏开发部 · 万能牌 Kei。',invite:'另外三台设备连接同一 Wi-Fi，打开下方链接。',backs:backSeat===viewer?`查看自己的${game?.side?'明':'暗'}面，仅自己可见；出牌仍使用当前启用的一面。`:`其他玩家朝外的${game?.side?'明':'暗'}面，随对局实时更新。`,log:'最近的出牌与效果。',leave:game&&room?'房间创建后保留 24 小时，离场不会清空手牌。在同一浏览器首页点击“返回牌桌”，或打开原邀请链接即可恢复；其他玩家可由房主切到单设备代为操作。':'离开后可重新创建或加入牌局。'} as Record<string,string>)[modal??'']}</DialogDescription>
 {modal==='online'&&<><label>你的昵称<input value={name} onChange={e=>setName(e.target.value)} maxLength={16} placeholder="输入昵称" autoComplete="nickname"/></label><Tabs value={tab} onValueChange={setTab}><TabsList className="room-tabs"><TabsTrigger value="create">创建房间</TabsTrigger><TabsTrigger value="join">加入房间</TabsTrigger></TabsList><TabsContent value="create"><div className="option-row"><span>加牌叠加 <small>只能接不小于上一张的数值加牌 · 无质疑</small></span><Switch aria-label="加牌叠加" checked={stacking} onCheckedChange={setStacking}/></div><div className="option-row"><span>相同牌抢出 <small>完全相同的牌可抢出，抢到者接管回合</small></span><Switch aria-label="相同牌抢出" checked={jumpIn} onCheckedChange={setJumpIn}/></div><div className="option-row"><span>排名赛 <small>前三人先后出完后结束，按出完顺序排名</small></span><Switch aria-label="排名赛" checked={finishMode==='ranking'} onCheckedChange={v=>{setFinishMode(v?'ranking':'first');if(v)setMatch500(false)}}/></div><div className="option-row"><span>500 分赛 <small>关闭时为单局胜负</small></span><Switch aria-label="500 分赛" disabled={finishMode==='ranking'} checked={match500} onCheckedChange={setMatch500}/></div><button className="primary full" disabled={busy||!name.trim()} onClick={()=>roomOp('create',{mode,name,stacking,match500:finishMode==='first'&&match500,jumpIn,finishMode})}>{busy?'创建中…':'创建四人房间'}</button></TabsContent><TabsContent value="join"><label>房间号<input aria-label="房间号" value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,'').slice(0,6))} placeholder="6 位房间号" maxLength={6}/></label><button className="primary full" disabled={busy||joinCode.length!==6||(!name.trim()&&!savedToken(joinCode))} onClick={join}>{busy?'连接中…':savedToken(joinCode)?'返回原座位':'入座'}</button></TabsContent></Tabs></>}
 {modal==='local'&&<><div className="local-names">{names.map((n,i)=><label key={i}><SeatBadge seat={i}/><input aria-label={`玩家 ${i+1} 昵称`} value={n} maxLength={16} onChange={e=>setNames(old=>old.map((x,j)=>j===i?e.target.value:x))}/></label>)}</div><div className="option-row"><span>加牌叠加 <small>只能接不小于上一张的数值加牌 · 无质疑</small></span><Switch aria-label="加牌叠加" checked={stacking} onCheckedChange={setStacking}/></div><div className="option-row"><span>相同牌抢出 <small>完全相同的牌可抢出，抢到者接管回合</small></span><Switch aria-label="相同牌抢出" checked={jumpIn} onCheckedChange={setJumpIn}/></div><div className="option-row"><span>排名赛 <small>前三人先后出完后结束，按出完顺序排名</small></span><Switch aria-label="排名赛" checked={finishMode==='ranking'} onCheckedChange={v=>{setFinishMode(v?'ranking':'first');if(v)setMatch500(false)}}/></div><div className="option-row"><span>500 分赛</span><Switch aria-label="500 分赛" disabled={finishMode==='ranking'} checked={match500} onCheckedChange={setMatch500}/></div><button className="primary full" disabled={busy} onClick={startLocal}>开始对局</button></>}
 {modal==='invite'&&<><input aria-label="邀请链接" readOnly value={inviteUrl} onFocus={e=>e.target.select()}/><p className="invite-note">房间号 <b>{room?.code}</b> · 手机长按链接可复制</p></>}{modal==='rules'&&<Rules mode={mode}/>}  {modal==='eggs'&&<EggGallery mode={mode} onPreview={cameo=>{setFx({id:Date.now(),type:'play',text:'彩蛋预览',cameo});tone('play')}}/>}
 {modal==='settings'&&<><div className="option-row"><span>隐藏顶部导航</span><Switch aria-label="隐藏顶部导航" checked={navHidden} onCheckedChange={v=>prefs('navHidden',v)}/></div><div className="option-row"><span>音效</span><Switch aria-label="音效" checked={sound} onCheckedChange={v=>prefs('sound',v)}/></div><div className="option-row"><span>战斗特效 <small>震屏、红屏、翻面与强化动画</small></span><Switch aria-label="战斗特效" checked={effects} onCheckedChange={v=>prefs('effects',v)}/></div><div className="option-row"><span>手机二次点击出牌 <small>开启后，再点选中的牌即可出牌；上划始终可用</small></span><Switch aria-label="手机二次点击出牌" checked={touchTapToPlay} onCheckedChange={v=>prefs('touchTapToPlay',v)}/></div><div className="option-row"><span>卡片高光 <small>卡面反光与扫光动画，默认关闭</small></span><Switch aria-label="卡片高光" checked={cardShine} onCheckedChange={v=>prefs('cardShine',v)}/></div><div className="option-row"><span>出牌人物卡片 <small>显示卡面角色的登场动画</small></span><Switch aria-label="出牌人物卡片" checked={showCameo} onCheckedChange={v=>prefs('showCameo',v)}/></div><button className="secondary" onClick={()=>{setModal(null);const type=mode==='flip'?'flip':mode==='flex'?'flex':'stack';setFx({id:Date.now(),type,text:'效果预览',amount:8});tone(type)}}>预览特效</button><button className="secondary" onClick={()=>setModal('eggs')}>卡牌头像</button><button className="text-button" onClick={()=>setModal('rules')}>规则与素材来源</button></>}
 {modal==='log'&&game&&<>{game.reveal&&<div className="challenge-proof"><h3>质疑时的手牌证据</h3><div>{game.reveal.map((f,i)=><span key={i}>{label(f)}</span>)}</div></div>}<ol className="event-log">{[...game.events].reverse().map(e=><li key={e.id}><span>{String(e.id).padStart(2,'0')}</span>{e.text}</li>)}</ol></>}
 {modal==='backs'&&game&&<><div className="opponent-detail-cards">{backFaces.map((f,i)=><PlayingCard key={i} card={{id:`inspect-${i}`,a:f}} selected={backIndex===i} onClick={()=>setBackIndex(i)}/>)}</div>{backFaces[backIndex]&&<p className="back-effect">{label(backFaces[backIndex])}：{cardEffect(backFaces[backIndex],false,1-game.side,game.players.filter((_,i)=>!game.rankings.includes(i)).length)}</p>}</>}
 {modal==='leave'&&<div className="dialog-actions"><button className="secondary" onClick={()=>setModal(null)}>继续玩</button><button className="primary" disabled={busy} onClick={leave}>离开牌桌</button></div>}
 </DialogContent></Dialog>
 <Dialog open={!inspectOther&&(!!pick||(!!game&&game.phase==='color'&&myTurn))} onOpenChange={o=>{if(!o)setPick(null)}}><DialogContent className="game-dialog" showCloseButton={game?.phase!=='color'}><DialogTitle>{needTarget?'选择目标与颜色':'选择颜色'}</DialogTitle><DialogDescription>{needTarget?'指定对手承受加牌，下一家照常行动。':'选择接下来跟随的颜色。'}</DialogDescription>{needTarget&&<div className="target-picker">{game!.players.map((p,i)=>i!==viewer&&!game!.rankings.includes(i)&&<button key={i} className={target===i?'active':''} onClick={()=>setTarget(i)}><SeatBadge seat={i}/>{p.name}</button>)}</div>}<div className="color-picker">{colors(game??{mode,side:0}).map(c=><button className={`color-${c} ${chosen===c?'chosen':''}`} key={c} aria-label={`选择${COLOR_NAMES[c]}色`} onClick={()=>setChosen(c)}>{symbols[c]} {COLOR_NAMES[c]}{chosen===c&&<Check size={18}/>}</button>)}</div><button className="primary full" disabled={!chosen||busy||!!(needTarget&&target===null)} onClick={()=>act(pick?{type:'play',id:pick.card.id,flex:pick.flex,color:chosen!,...(target!==null?{target}:{})}:{type:'color',color:chosen!})}>确认出牌</button></DialogContent></Dialog>
 </main>
}


